### ISSUE TITLE
Errors on project

### ISSUE THREAD

**Issue by JaydenC39** [techwithtim/5-Python-Projects-For-Beginners#17]
here's the problem:
Traceback (most recent call last):
  File "c:\Users\catdo\Desktop\Jayden\Apps\Python\VS Code Files\Password Manager\passwords_manager.py", line 17, in <module>
    key = load_key()
  File "c:\Users\catdo\Desktop\Jayden\Apps\Python\VS Code Files\Password Manager\passwords_manager.py", line 11, in load_key
    file = open("key.key", "rb")

Hope you can help me with this!

**Comment by its-your-invi** [comment]
You have made a new directory "Password Manager". I think you forgot to transfer the "key.key" file to your new directory that's why the error is occurring.

**Comment by its-your-invi** [comment]
> thanks

Close this issue if it's resolved
